language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpunit --coverage-clover=clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs; fi
  - if [[ $PHPCS = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
